[configure]
command:/usr/local/opnsense/scripts/OPNsense/GwActions/setup.php
parameters:
type:script
message:generate gateway actions configuration

[status]
command:/usr/local/opnsense/scripts/OPNsense/GwActions/engine.py --status
parameters:
type:script_output
message:report gateway actions status

[event]
command:/usr/local/opnsense/scripts/OPNsense/GwActions/engine.py
parameters:%s
type:script
message:handle gateway event for %s

[runrule]
command:/usr/local/opnsense/scripts/OPNsense/GwActions/engine.py --run-rule
parameters:%s
type:script_output
message:manually run gateway action rule %s

[clearhistory]
command:/usr/local/opnsense/scripts/OPNsense/GwActions/engine.py --clear-history
parameters:
type:script_output
message:clear gateway actions history
